### ISSUE TITLE
Lobby: Clicking new game button before the animation finishes its load in causes deck selection to break. 

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#101]
I just entered the Decider's name, and then double-clicked quickly on the "Start New Game" button, and this appeared: 
![screen shot 2017-04-07 at 1 38 08 pm](https://cloud.githubusercontent.com/assets/12397944/24812285/7516b870-1b97-11e7-9fb8-910323ad6d8a.png)

**Comment by mattwbenson** [comment]
In this state, it's impossible to continue--clicking "next" loads the "Deck not Specified" error

**Comment by jpailthorpe** [comment]
I have seen this a few times including on friday. Not sure what is happening, but I think it is breaking enough to become a problem we need to prioritize.

**Comment by jpailthorpe** [comment]
I am going to try and reproduce this on the app

**Comment by jpailthorpe** [comment]
This is still happening for me, but the only way to reproduce it is by clicking new game BEFORE the rest of the animation finishes. once the animation is finished, even if you mash the button a million times it won't break. However, even ONE press before the animation of the buttons and logo loads in will cause this breakage.
