### ISSUE TITLE
UX: "Deck not selected" error message loads below the active viewport, very easy to miss

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#102]
While it's difficult to reach a state where a player tries to start a game without a deck selected, in the rare event that it happens, it's very difficult to notice the error message, as it loads "underneath" the game screen. Essentially, the only way to see that a new element has loaded is noticing that the scroll bar has rescaled itself. 
![screen shot 2017-04-07 at 10 31 35 am](https://cloud.githubusercontent.com/assets/12397944/24812459/27a3f368-1b98-11e7-8d60-b38ac825ae5d.png)

**Comment by jpailthorpe** [comment]
This is no longer possible, closing
