### ISSUE TITLE
Brainstorm: update brainstorm templates to match new mockups

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#115]
I noticed this happen in 1 out of 3 groups, mostly with older players. When hitting the brainstorm phase, even with the copy that tells them to think to themselves quietly, the name "brainstorm" suggests collective thinking. Since this group was also plagued with the players keeping their role cards open and the decider somewhat skimming through the instructions quickly, this contributed to this problem. 

therefore, though we have copy in place that tells players what to do, and we can never control for every single player attention variable, having the name changed to "Think" would be an additional safeguard against this happening.  I will update mockups and copy to address this, and when ready, assign dev for implementation. 

Funny enough, back in 2015 this problem also appeared, and the old dev. team decided to change the phase name to "Think". Somehow this never made it into the Unity version, which is why we didn't catch it.

**Comment by jpailthorpe** [comment]
- [ ] @johnnycrich change phase bar to think 
- [ ] Jordan will update copy  mockups and pass to johnny when ready

**Comment by johnnycrich** [comment]
Copy references to brainstorm now say 'think' in all UI.

**Comment by jpailthorpe** [comment]
I update much of the text in the brainstorm phase to include these changes. lets double check its 1:1, make changes, and then move to review!

**Comment by jpailthorpe** [comment]
major change fulfilled. still some differences between mockup and game but these are copy and i can change myself.
