### ISSUE TITLE
MeetPhase: Flow + copy + logic needs updating to direct player introductions in game

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#118]
Right now stakeholder introductions are done informally when the decider reads the directions on this screen: 

![meet_2_decider_sharerole_v1](https://cloud.githubusercontent.com/assets/10051544/24880705/6869f4ec-1e09-11e7-8adb-5a7a310ec465.png)

but if the decider skips over this screen or misses the instruction, the game can advance on without player's telling each other who they are, creating a confusing experience. The way the pitch phase works where the decider tells each player to introduce themselves and once done presses next will solve this problem. 

I will update the mockups and then assign to dev team to implement. @johnnycrich feel free to get a head start on updating logic if you think it is beneficial.

**Comment by jpailthorpe** [comment]
for time, we will only have the text box change based on the name of the player, but it won't be any different from player to decider, besides the action box text and the next button (only on decider screen). 

Please wait for mockup update for Dev

**Comment by jpailthorpe** [comment]
working on this now fyi

**Comment by jpailthorpe** [comment]
just pushed updates for the meet phase. This includes text as well so please note this when updating templates!

**Comment by mattwbenson** [comment]
Resolved, but see issue #176
