### ISSUE TITLE
Decide: Modals for Proposal + Agenda results are much too quick, doesn't allow players to read. 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#120]
one quick fix is doubling the time before it disappears. Lets try simply doubling the time first, and also give me some instructions on where to find these values in code so I could play with it myself. 

Another option would be including a button on the player the modal is addressing for them to acknowledge the update and advance along. This might be a better ultimately, but might take too much time compared to everything else we need to do. I want to test timing changes first before changing logic/introducing additional potential problems.

**Comment by esalling23** [comment]
decide modal duration is now a field in the game config settings in keystone!

**Comment by jpailthorpe** [comment]
please verify fix and change Matt!
