### ISSUE TITLE
EndGameDebrief: Integrate debrief screens after last round.

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#127]
At this time, the game does not incorporate end of game debrief questions. We want this to be a direct part of the experience. Though very light in terms of design and dev. it is a non-negotiable piece of the experience and therefore needs to be in before shipping. 

Debrief questions ideally would be accessible from the landing page as well, but we will address that in potential other milestone. 

- [x] create mockups/copy/logic for debrief phase.
- [x] Pass to dev for Implementation.

**Comment by jpailthorpe** [comment]
Template will be four screens using the same speech bubble framework. We will try to push for the player who wins the game leads the discussion, but this might not make it in logic wise. The decider of round three will lead the discussion. ideally we will have the winner of the game in this position, but this is a secondary goal.

**Comment by jpailthorpe** [comment]
I just updated zeplin to include the debrief screens.

**Comment by johnnycrich** [comment]
@jpailthorpe There is now a basic version of this on QA. You will need to add the debrief questions in the CMS. The phase bar is still present for this screen; will fix later.

**Comment by jpailthorpe** [comment]
added questions on both Qa and production

**Comment by jpailthorpe** [comment]
fixed! it works! yay!
