### ISSUE TITLE
iOS: Decks have offset formatting on initial load

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#133]
This was on iPad during game creation. After I minimized the window to take/send the screencap, the formatting corrected itself, though. 
![img_0055](https://cloud.githubusercontent.com/assets/12397944/24915013/fa862838-1ea3-11e7-8f70-9ec9dc8a0160.PNG)

**Comment by jpailthorpe** [comment]
We are going to remove w stakeholders and only display 2. so once that is fixed, this SHOULD be okay again.

**Comment by jpailthorpe** [comment]
I didn't see this today testing on 6s as initial decider/host.

**Comment by mattwbenson** [comment]
I'm still seeing this on the iPad 4 and the iPod touch, tagging them on this issue.

**Comment by esalling23** [comment]
@mattwbenson please check this on the new build which reduces stakeholder roles to 2 - may happen to be a fix for this
