### ISSUE TITLE
iOS: UI not appearing on phone-sized devices

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#134]
Not sure if this is actually an iOS-specific problem, but I'm only seeing it on the iPhone and iPod touch, not my samsung phone. This is occurs right when the player gets to /play
![img_0004](https://cloud.githubusercontent.com/assets/12397944/24915401/08b64748-1ea5-11e7-85bb-f106b7eb03fa.PNG)

**Comment by jpailthorpe** [comment]
testestest

**Comment by jpailthorpe** [comment]
this is not happening on QA on ipod touch, both in chrome and safari, and on ios 9 and 8. 

however, on production, the ipod touch ios 9 is fine, while ios 8 does NOT work. this has to be a problem with ios 8 on production.
