### ISSUE TITLE
PitchPhase: Update pitch phase templates to match new mockups

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#137]
Currently the copy in game mentions that the screen will display the order of speakers, but this is not functionally in place just yet, and therefore copy needs to be updated to reflect current game state until new functionality is in place.

**Comment by jpailthorpe** [comment]
updated all copy and screens in pitch phase. please review and make changes. once they are 1:1, lets build and move to review!

**Comment by johnnycrich** [comment]
@jpailthorpe Copy is updated now in pitch phase.
