### ISSUE TITLE
DecidePhase: Modals that list a player's coin value as more than 3 spaces (1000) creates line padding issues.

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#144]
This happened on all devices, but we think it has to do with long character names. Though the ten character count limit on names are set, the modal might not be set correctly for ten characters. 
see examples: 

![img_0032](https://cloud.githubusercontent.com/assets/10051544/24977352/c70c5df4-1f9a-11e7-9a6e-770681fdb2d8.PNG)

![img_0033](https://cloud.githubusercontent.com/assets/10051544/24977357/ca97cb98-1f9a-11e7-8b8f-2dda616da316.PNG)

**Comment by jpailthorpe** [comment]
I think this is actually because of the 1000 coins in line 2 possibly?

**Comment by jpailthorpe** [comment]
Keep in ind after seeing this initially, we could not reproduce this. Not sure.

**Comment by esalling23** [comment]
@jpailthorpe the reason why the first screenshot couldn't be reproduced is because the number of coins (1000) is pushing that block down, but in the second screenshot that user only has 800 coins which doesn't push the player name block down!
