### ISSUE TITLE
Reconnection_DoubleDown: upon player refresh, that specific player is sent to the start of the phase, but all other devices are stuck in same position. 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#145]
upon player refresh, that specific player is sent to the start of the phase, but all other devices remain in same stuck position.  If other players do refresh, their screen changes to the start of the current phase as well. The decider can refresh their screen, but they are then taken to the lobby (see #68 ) and screen on other player's devices aren't affected. Error message doesn't appear in this instance. only way out was to close the tab.   This was not device specific and happened across all testing environments.

**Comment by johnnycrich** [comment]
@jpailthorpe who is "that specific player"?
