### ISSUE TITLE
Pitch/DoubleDown: when selecting option in modal under double down, after selecting an option sometimes the modal disappears and breaks the game 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#146]
matt selected to buy more time in pitch, after selecting to buy time, the dialog made it look like it was going back to the decider. all other devices had the waiting modal. Around a few seconds after that, the host got kicked (received orange "yikes" game server crash screen)  while all other devices remained on the waiting modal.  Matt's device then showed the choice modal again, seemingly like it wasn't clicked at all. 

We think the host getting a "game server" crash is unrelated, or at least we weren't able to reproduce that aspect of this bug. The problem of selecting and option and then the game begin stuck in a weird state where the modal is not there but the template screen is, while everyone is expecting a choice still, was reproducible multiple times following the steps above, using the test devices and following the same actions. However, we couldn't get it to trigger every single time, and we did see it on both the moto G and the ipod, so it wasn't device specific. 

Therefore we think it has something to do with socket and relay of information, though we aren't sure about anything more than that. No errors in the console were found on devices.

**Comment by johnnycrich** [comment]
I am unable to repro. May have been addressed by another fix.

**Comment by jpailthorpe** [comment]
I haven't seen this after 3-4 times playing today.
