### ISSUE TITLE
Landing Page/Mockup differences

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#15]
- [x] Issue with bullet list in the top section.

- [x] ~~Scrolling issue/short height of flow-of-play section~~ Image in section failed to import from old database, reuploaded and fixed.

- [x] ~~Wonky formatting of graphics in flow-of-play section.~~ (See above)

- [x] Type color

- [x] Top section has too much padding on mobile

- [x] Top Landing Graphic might be too large on smallest device screens.

- [ ] Missing graphic that covers top two sections.

- [ ] Because one of the lists was cut between the mockup and the site, there is a layout graphic missing from the introduction. 

NOTE: Many of these issues popped up between my commits, so it's likely that some global CSS definitions are targeting elements or classes on the landing page.

**Comment by jpailthorpe** [comment]
just keeping for my review for now.
