### ISSUE TITLE
ScorePhase: When players submit coins to the pot by buying time those extra coins appear in the pot, but are not transferred to the winning player. That player still only receives the amount of coins the pot started with at the beginning of the round (200).

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#151]
When a player chose to buy time in the pitch phase for 100 coins, the coin pot was updated to 300. However, when the player who won the proposal received their coins, they only received 200 coins, and the coin pot showed 100 coins remaining when choosing hidden agenda items. Therefore, I think the coin pot is not giving over the entirety of the accumulated coins it acquires during the round. Once a new round starts, the coin pot is reset to the value in keystone. This is a game design problem as it breaks the idea of putting coins into the pot and ramping up the stakes of the score.

**Comment by johnnycrich** [comment]
I was not able to reproduce.

**Comment by mattwbenson** [comment]
I'm in the middle of a 5-person game where I just had some related behavior occur. After having the first non-decider player buy additional time twice, and then the following player buy additional time once, even though both players were deducted the correct amount of coins, the amount of coins in the pot stayed at 500 throughout.

**Comment by jpailthorpe** [comment]
Im going to try to reproduce what matt said above.

**Comment by jpailthorpe** [comment]
could not reproduce the pitch/coin problem with the pot staying at 500. I think it was fixed from previous pushes today.
