### ISSUE TITLE
Round2+_DeciderTimer:  After the decider from round 1 became a player in round 2, they never saw a timer on their screen when it was supposed to appear. 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#153]
iphone6s was the first decider in round 1. They made the desktop the new decider in round 2. When the timer first appeared in the brainstorm phase, 6s didn’t see a timer at all, but received the correct actionbox text and templates. No errors occurred, it was just hidden from view/not shown.

I am almost positive this occurred on the desktop player when it got to round 3, not showing timers on their screen even though they went from player to decider, though I can’t verify this part 100%.

**Comment by johnnycrich** [comment]
I made a fix for this.

**Comment by jpailthorpe** [comment]
confirmed fixed
