### ISSUE TITLE
DecidePhase_PlayerModal:  Player screen modal does not show accurate coin values updated as coins are distributed. 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#154]
This is referring to this screen:

![decide_1_player_proposalselection](https://cloud.githubusercontent.com/assets/10051544/24983456/1371d984-1fb5-11e7-85cc-8d6d23e9f576.png)

It creates confusion when a player sees themselves receive 200 coins by winning an agenda item, but don’t see that score updated when the next agenda item is up for deciding. The values DO update in the player’s bottom bar. A quick fix for this would be to simply remove the grey colored coin values from the player’s modal.

**Comment by esalling23** [comment]
coins have been removed from these modals for now
