### ISSUE TITLE
Lobby: "Back" and "Play" buttons are hard to see/press on small phone-sized devices

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#158]
![img_0147](https://cloud.githubusercontent.com/assets/12397944/25046164/017dab46-20fe-11e7-8920-840531e952e7.PNG)

This was on the iPod Touch.

**Comment by jpailthorpe** [comment]
I am going to either redesign the lobby screen to account for screen spacing on small devices in browser, or we are going to not allow folks to play in browser on iOS devices 5 and below,  redirecting them to download the app. This will hopefully resolve this problem. I will place this in the icebox for now.

**Comment by jpailthorpe** [comment]
Finished complete overhaul redesign of lobby to address this and many other issues.
