### ISSUE TITLE
Lobby: 5th player's name appears outside the lobby window on small mobile devices 

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#159]
![img_0148](https://cloud.githubusercontent.com/assets/12397944/25046330/dc7ee886-20fe-11e7-987f-05f10bf6a81b.PNG)

**Comment by jpailthorpe** [comment]
I am going to either redesign the lobby screen to account for screen spacing on small devices in browser, or we are going to not allow folks to play in browser on iOS devices 5 and below, redirecting them to download the app. This will hopefully resolve this problem. I will place this in the icebox for now.

**Comment by jpailthorpe** [comment]
updated and fixed
