### ISSUE TITLE
LandingPage: End of text lines showing strange characters

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#16]
Probably when the database merge happened. Please check if this is represented in the CMS. If so, remove extra characters. If in code, remove and review why/how this happened so we know in the future (making sure it doesn't happen when pushing builds, etc.) 

![1_websitecontentbreaking](https://cloud.githubusercontent.com/assets/10051544/24111134/d6bc33d2-0d6b-11e7-802c-2c99d4fbc2ca.png)

**Comment by johnnycrich** [comment]
This is a database issue. I will look into it.

**Comment by jpailthorpe** [comment]
just flagging this is still a thing. It isn't appearing in CMS nor could I find it in code.

**Comment by jpailthorpe** [comment]
this is a priority before monday just fyi
