### ISSUE TITLE
Leaderboard: Assets not loading, layout breaking on small mobile devices

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#161]
![img_0149](https://cloud.githubusercontent.com/assets/12397944/25047408/7c393002-2104-11e7-9db1-5dc1e5dd2ba2.PNG)

This is on iPod Touch.

**Comment by johnnycrich** [comment]
@mattwbenson If this happens again definitely want to know what the console says.

**Comment by esalling23** [comment]
@jpailthorpe cannot reproduce this on production - can we move it to 'done'?

**Comment by jpailthorpe** [comment]
yes, moving to done for now. We will start a fresh QA process for ipod size devices once we tackle new layout stuff. If its not fixed we will create a new issue
