### ISSUE TITLE
Round 3 Leaderboard: All selectable options collapsing into each other on small devices as Decider in Decision Phase

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#167]
![img_0152](https://cloud.githubusercontent.com/assets/12397944/25050603/6f70c24c-2116-11e7-83dc-6e20718f5800.PNG)

**Comment by mattwbenson** [comment]
This behavior also affects the "Yes" and "No" buttons for the hidden agenda item selections:
![img_0153](https://cloud.githubusercontent.com/assets/12397944/25050731/0742291c-2117-11e7-9fdc-0a25152d610b.PNG)

**Comment by esalling23** [comment]
@jpailthorpe cannot reproduce on production - can we move to 'done'?
