### ISSUE TITLE
PItchPhase: Coins players pitch into the pot are not increasing the pot value 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#169]
I noticed this was a comment by matt on the scoring issue I made #151  . Though related, feels like a different issue, so posting here. Lets see if we can reproduce. 

"In a 5-person game. After having the first non-decider player buy additional time twice, and then the following player buy additional time once, even though both players were deducted the correct amount of coins, the amount of coins in the pot stayed at 500 throughout.

Double down is working correctly"

**Comment by esalling23** [comment]
confirmed fixed on production
