### ISSUE TITLE
ORG/AppleStore: Prep assets and materials for Google/Apple store submissions, priority on Apple

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#172]
In order to support play on mobile devices we will need to get the app into the appstore/googleplay store. The browser play also introduces lots of potential issues with connection/refresh which hinders the experience. The app is designed to satisfy these small devices without this extra browser screen bloat AND creates a more technically stable mobile solution. 

Therefore, in order to support these devices, we will need to get the app into the store. Though at this point I think we still leave the option to play in mobile browsers, I HIGHLY recommend folks who are playing on a phone use the app, especially when in workshop/facilitated sessions. 

Apple Requirements
[Apple ](https://developer.apple.com/app-store/review/guidelines/)
[Breakdown of assets and things needed ](https://www.raywenderlich.com/127939/submit-an-app-part-2)

- [x] App Icon (29, 40, 58, 76, 80, 87, 114, 120, 152, 167, 512, 1024px -- all square)
- [x] Retina-sized logo on desired background color for app splash screen
- [x] Keywords 
- [x] Game Description 
- [x] Feature list 
- [x] Screenshots (2-4) on iphone 5 size (Jordan)
- [x] category 

[Google](https://developer.android.com/distribute/best-practices/launch/launch-checklist.html) 
[Quality Guidelines](https://developer.android.com/develop/quality-guidelines/index.html)
[App Listing Checklist ](https://developer.android.com/distribute/best-practices/launch/store-listing.html)
[Specific Dimensions and graphic design details for assets ](https://support.google.com/googleplay/android-developer/answer/1078870#feature_graphic_requirements)

- [x] App Icon (36, 48, 72, 96, 144, 192, 512px, all square)
- [x] App splash screen (PNG) sized for hdpi, mdpi, xhdpi, xxhdpi, xxxhdpi
- [x] Game Description 
- [x] Feature list 
- [x] [Launcher Icon ](https://developer.android.com/guide/practices/ui_guidelines/icon_design.html#design-tips) (36 , 48, 72, 96, 144px) 
- [x] high res listing icon (32-bit PNG (with alpha)Dimensions: 512px by 512px Maximum file size: 1024KB)
- [x] Screenshots (2-4) on phone (JPEG or 24-bit PNG (no alpha)Minimum dimension: 320px Maximum dimension: 3840px)
- [x] category

**Comment by jpailthorpe** [comment]
@aidanrae If you want to hand this off to a lab assistant that is also fine with me. We just need it by May 1.

**Comment by jpailthorpe** [comment]
## Game Description:

@Stake is a online digital multiplayer game that fosters empathy and creativity between diverse perspectives on real-world issues

Addressing different perspectives while solving complex social problems is a science and an art. At times, the barriers between overcoming community divides and biases to solve local problems can feel impenetrable. 

@Stake was created to help facilitate productive and fair conversations in classrooms, conferences, strategic board meetings, and public events. By playing @Stake, participants learn that productive conversations thrive off of authentic listening and multiple perspectives. From infrastructure needs to inter-agency collaboration and PR campaigns, @Stake can be used to explore a variety of issues in your communities. In the past, it's been used for:
Participatory Budgeting Priorities Comprehensive, Urban Planning Issues, Countering Youth Unemployment, and more! 

@Stake is played with 3-5 players in the same room. After introducing their character’s perspectives, players jump into brainstorming mode to think of solutions to public issues. Players then take turns proposing their ideas and arguing their point of view to the table’s Decider. The group debates to reach a solution that is best for all through intense deliberation. The best ideas that emerge from the deliberations win!

## FEATURE LIST

Empathy Building
Whether you’re playing the role of a recent immigrant, a staff member in the Mayor’s office, or a small business owner, players gain a deeper understanding of diverse community needs by considering different perspectives.

Creative Brainstorming
Through fast-paced rounds, players think quickly on their feet to brainstorm the most creative ideas and collaborations from the perspectives of their assigned characters.

Practicing Deliberation
During lightning rounds, players analyze each other's ideas and balance different agendas to reach a winning solution.

**Comment by johnnycrich** [comment]
@jpailthorpe For the Google Play store we need a "Short Description" w/ max limit of 80 chars.
