### ISSUE TITLE
UX/iOS: Hidden Agenda items getting forced out of layout, are made unreadable

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#174]
![img_0155](https://cloud.githubusercontent.com/assets/12397944/25137328/731614ee-2425-11e7-8ee2-e8fd1ba025d1.PNG)

**Comment by esalling23** [comment]
known issue

**Comment by esalling23** [comment]
@mattwbenson duplicate of #95 please add anything to that issue
