### ISSUE TITLE
MeetPhase: Decider asked to introduce self with non-existent character title

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#176]
This player was the decider, and the first to be asked to introduce themselves. They're asked to introduce their character title, but without a role card or clearer copy, this is a confusing instruction. 

![screen shot 2017-04-18 at 11 15 00 am](https://cloud.githubusercontent.com/assets/12397944/25138358/504f0e40-2428-11e7-83aa-65cf53e8f6ab.png)

**Comment by jpailthorpe** [comment]
seems like we just need to exclude the decider in the introductions.
