### ISSUE TITLE
iOS: Modals loading noticeably slower

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#178]
This seems to be a safari issue, as older devices that run android/chrome aren't having issues. Whatever the case, the iPod touch and iPad 4 take an additional 5-10 seconds to load any modal at any point in the game than other devices. This wasn't occurring in previous builds.

**Comment by jpailthorpe** [comment]
this has been not re-occuring, and possibly happened due to dev tools increasing load. OR it was something strange happening in a build. either way, closing for now.
