### ISSUE TITLE
Buy More Time Modals appear before animated in -- content wiped after

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/at-stake-v3#181]
<img width="1280" alt="screen shot 2017-04-18 at 12 46 05 pm" src="https://cloud.githubusercontent.com/assets/11821504/25142616/9802a42e-2435-11e7-8ded-0e9438ea91c2.png">

- The modal appears during the timer - is not game breaking
- The modal then appears as normal (animates in) and player can choose to buy time or not
- Player chooses to not buy time - modal closes fine
- Both desktop players have no game content (includes decider, which breaks game)

<img width="1280" alt="screen shot 2017-04-18 at 12 47 32 pm" src="https://cloud.githubusercontent.com/assets/11821504/25142664/c6c8af74-2435-11e7-863e-af3ed47a87bb.png">

- Both mobile devices show up fine, waiting for decider to start timer. 
- No one was kicked out.

**Comment by johnnycrich** [comment]
Cannot repro.

**Comment by esalling23** [comment]
unable to reproduce - @jpailthorpe not sure if this should be moved to 'done'
