### ISSUE TITLE
"Start Timer" and "Seconds Left" changes timer circle size

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/at-stake-v3#183]
Timer is correct size with "Start Timer" but then increases in size to accommodate the "Seconds Left" copy 

- "Seconds left" should be made smaller to keep timer consistent

**Comment by jpailthorpe** [comment]
I actually remade this design as well, and we will most likely rebuild this when they are ready to go.

**Comment by esalling23** [comment]
Timer is now up-to-date with the current design except for one thing: the white stroke line around the timer is still half the width of the blue stroke. I was not able to figure out a way to fix this while still keeping the design. Will return to do this later on, @jpailthorpe confirmed this is not priority
