### ISSUE TITLE
Winning Player not receiving coins 

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/at-stake-v3#184]
- Player who won previous round is not receiving pot even when next round starts (not live)
- Player with chosen proposal does not see their pot update when they win (live)

Players are not receiving winning coins at all - they start each round with the coins they ended with the previous round, ignoring any winnings, proposal or agenda.

**Comment by esalling23** [comment]
UPDATE: Players are getting points live time for agenda items

**Comment by johnnycrich** [comment]
I saw this once and then not again. Please try to keep reproducing, noting exact player actions taken.

**Comment by esalling23** [comment]
confirmed fixed on production
