### ISSUE TITLE
End of game: Debrief not appearing after score phase. 

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/at-stake-v3#186]
- [ ] Change copy to say "Play again" or "End game" 
- [ ] Change button to redirect players to lobby screen

Currently this button just sends players to an empty round screen
<img width="425" alt="screen shot 2017-04-18 at 1 41 45 pm" src="https://cloud.githubusercontent.com/assets/11821504/25144701/cac440aa-243c-11e7-9f3a-42c710837862.png">

**Comment by jpailthorpe** [comment]
verified this is happening after selecting "go to next round button". 

<img width="848" alt="screen shot 2017-04-18 at 3 30 05 pm" src="https://cloud.githubusercontent.com/assets/10051544/25149326/064dcb8c-244c-11e7-9a66-5335b7ac83ad.png">

**Comment by jpailthorpe** [comment]
fixed!
