### ISSUE TITLE
PitchPhase: Upon refresh, Player's coin value never reappears. 

### ISSUE THREAD

**Issue by ritsukaBin** [engagementgamelab/at-stake-v3#187]
-Press the "Reconnect" button in the menu on player's screen during the Pitch phrase

-The value number of coin missing from the screen
<img width="1440" alt="screen shot 2017-04-18 at 2 03 50 pm" src="https://cloud.githubusercontent.com/assets/20562141/25145774/e197cc2c-243f-11e7-9914-7e91580d660a.png">

**Comment by ritsukaBin** [comment]
update: 
If the number will reappear after coin value is change (use for buying more time)
<img width="1440" alt="screen shot 2017-04-18 at 2 23 02 pm" src="https://cloud.githubusercontent.com/assets/20562141/25146683/c2c13538-2442-11e7-80db-804109051f6f.png">
<img width="1440" alt="screen shot 2017-04-18 at 2 23 09 pm" src="https://cloud.githubusercontent.com/assets/20562141/25146694/d614a480-2442-11e7-948a-fc4517ef031c.png">

**Comment by jpailthorpe** [comment]
saw this yesterday. confirmed it is still happening!

**Comment by jpailthorpe** [comment]
this is happening in any phase fyi
