### ISSUE TITLE
LandingPage_iphone5: global row padding is making mobile margins much too intense, need to incorporate accurate media queries

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#19]
I think this is due to improper setting of media queries and/or making sure global css parameters are not messing with this. 

![4_website mobile _margin much too wide image too small](https://cloud.githubusercontent.com/assets/10051544/24111426/b8b4bb10-0d6c-11e7-8081-8b8ea54ff44e.png)

![4 1_website mobile _need to disable row padding at breakpoint](https://cloud.githubusercontent.com/assets/10051544/24112069/c68732a2-0d6e-11e7-9e42-a96a1d56e7e9.png)

**Comment by mattwbenson** [comment]
This changed between builds, @jpailthorpe does this still need to be tweaked?

**Comment by mattwbenson** [comment]
This was a problem with the base layout file not assigning the homepage its own viewport meta tag.

**Comment by jpailthorpe** [comment]
Still seeing this on iphone 6s plus. But like the other issues, no worries until we turn our attention back to this and tackle it together!
