### ISSUE TITLE
LandingPage_Global: Review media queries and CSS construction

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#20]
We need to do a thorough overview of breakpoints to make sure all global parameters aren't being applied to every device size. Good widths are as follows: 

320 (iphone 5)
375 (iphone 6
414 (iphone 6+)
768 (ipad portrait)
1024 (desktop small
1440 (desktop medium) 
1920 (desktop large) 

some of these might be a bit overkill (such as limiting to one out of iphone 6 + iphone 6plus) but the rest are important enough to warrant a review. 

([this site ](https://responsivedesign.is/develop/browser-feature-support/media-queries-for-common-device-breakpoints/)gives max heights too, but this is mostly for the app and wouldn't apply to the site)

would like input from you @johnnycrich on a better approach if applicable, ultimately just making sure we are all on the same page and understand the user experience goal here.

**Comment by jpailthorpe** [comment]
And to clarify, I actually am not suggesting device specific breakpoints, but instead, having content drive those breakpoints. only offer those above to think about a super rough baseline. once we get this version of the app ready for April 3, I am going to try and use Fluid layout (a sketch plugin) to better convey what I mean by this. 

So basically, I am in agreement with this: 
https://responsivedesign.is/strategy/page-layout/defining-breakpoints/

and this: 
https://responsivedesign.is/articles/why-you-dont-need-device-specific-breakpoints/

even though it sounds like I am saying the opposite :P . Still would like to talk through this so we can find a solution that makes sense on both engineering/user experience and doesn't kill our short dev. windows.

**Comment by mattwbenson** [comment]
See #9 , seems to be last major issue re: media queries. For documentation, many of these formatting issues seem to be linked to the landing page losing its viewport meta tag at some point--restoring it fixed those problems.

**Comment by jpailthorpe** [comment]
good to know! I am going to hitch this into the landing page fixes we will need to review once johnny is in hawaii.
