### ISSUE TITLE
UX: Rolecard Height is short, making it look a little strange on large devices. 

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#208]
iPad 4:
![img_0011](https://cloud.githubusercontent.com/assets/12397944/25533729/9180ef12-2bff-11e7-951d-a9639a743dc9.PNG)

iPod:
![img_0034](https://cloud.githubusercontent.com/assets/12397944/25533780/c11b4b3c-2bff-11e7-8a3d-8921168ba10b.PNG)

**Comment by jpailthorpe** [comment]
also noticed this on friday playthrough. possibly due to line height and padding LR

**Comment by esalling23** [comment]
@jpailthorpe is this mid-redesign? Or is it ready for implementation

**Comment by esalling23** [comment]
@mattwbenson I think we should go ahead and do a review of this

**Comment by mattwbenson** [comment]
This is fixed on everything except the iPod Touch

**Comment by jpailthorpe** [comment]
I haven't seen a problem with legibility today (though haven't tested on iphone5), but the design looks a little wonky just due to variance in height on the full card and where it lands on the screen after opening. Is there a way to make it so that the entire modal is centered on devices like it is in the mockup? That would be ideal.

**Comment by jpailthorpe** [comment]
If we change the role card inner elements to not force a particular width px value and stop forcing a height of 458px on the main div (instead switch to auto) we can make it look nicer.
![screen shot 2017-05-05 at 4 01 02 pm](https://cloud.githubusercontent.com/assets/10051544/25762383/92b39df0-31ac-11e7-91a1-f92b6a9d5b17.png)
![screen shot 2017-05-05 at 4 02 32 pm](https://cloud.githubusercontent.com/assets/10051544/25762384/92b79b9e-31ac-11e7-860b-5f6e632d4666.png)

**Comment by jpailthorpe** [comment]
![screen shot 2017-05-05 at 4 06 20 pm](https://cloud.githubusercontent.com/assets/10051544/25762509/fdb22c52-31ac-11e7-8287-24d963333f0b.png)

**Comment by jpailthorpe** [comment]
also the border color is set to #fff and it should be #ebebeb

**Comment by jpailthorpe** [comment]
fixed with the new role card modal
