### ISSUE TITLE
LandingPage_iphone5: Title text cutting off on right side of screen in mobile view. 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#21]
![5_website mobile _title text cutoff on right side](https://cloud.githubusercontent.com/assets/10051544/24112106/da589ba4-0d6e-11e7-8db0-4f24dc042d92.png)

**Comment by mattwbenson** [comment]
Tweaked overflows so they shouldn't clip anything, needs review
