### ISSUE TITLE
UX: iPad: Leaderboard entries cutting off player names/icons

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#210]
iPad 4:
![img_0012](https://cloud.githubusercontent.com/assets/12397944/25534743/ce8c5f10-2c02-11e7-8e54-9fb3075d98f1.PNG)

**Comment by jpailthorpe** [comment]
I am going to try and recreate this.

**Comment by mattwbenson** [comment]
This particular layout issue is fixed, but the leaderboard is still displaying in a broken way across all devices:

iPad:
![screenshot_2017-05-03-14-20-04](https://cloud.githubusercontent.com/assets/12397944/25675666/51e6c6a8-300d-11e7-9d41-0e136c1c867a.png)

Galaxy Note 2:
![screenshot_2017-05-03-14-28-40](https://cloud.githubusercontent.com/assets/12397944/25675692/6a8abf70-300d-11e7-9b44-4667307d9f0a.png)

**Comment by johnnycrich** [comment]
@jpailthorpe What was the reasoning behind a layout change for the leaderboard vs a couple weeks ago? Was this to accommodate iPod/Safari? There isn't much space for points and icons.

**Comment by jpailthorpe** [comment]
on first glance it looks like the text sizing of the 1st, 2nd, etc are much too big, which might be causing layout breakage.

**Comment by jpailthorpe** [comment]
also green boxes are not correct width, which actually might be the cause too. let me know if you need more direction on this and i can drill down @esalling23

**Comment by jpailthorpe** [comment]
also height of container is much too small (most likely due to reusuing the proposal choice modal box, but that only ever needs four players while this needs five, meaning we just need to have it be a dif component.

**Comment by esalling23** [comment]
@mattwbenson please review this in new build
