### ISSUE TITLE
UX: All devices: Below-timer prompts break out of their div if 3+ lines long

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#211]
On iPad 4, but this is happening on all of our QA devices:

![img_0013](https://cloud.githubusercontent.com/assets/12397944/25534892/4c8f5660-2c03-11e7-91b1-340d70a75d3e.PNG)

**Comment by jpailthorpe** [comment]
just need to decrease the padding on LR side of text. All text should fit properly otherwise.
