### ISSUE TITLE
Gamebreaky: Pitch: Player given option to buy additional time, but doesn't actually receive it

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#212]
This has happened to me in both Pitch rounds of this match. I'm playing with the iPod Touch, MotoG, iPad 4, and on chrome desktop. Play proceeds normally until the iPod touch is given the option to buy additional time. If the iPod Touch player chooses to buy more time, the modal will disappear and the chime will play as if the timer has restarted, but the timer stays at zero, and the game does not proceed for any of the other players. If the player refreshes the iPod Touch, the modal will re-appear, but buying more time again only re-creates this behavior. The only way to advance out of this state is to either decline buying additional time from the outset, or to refresh the device and then decline.

**Comment by mattwbenson** [comment]
Just had this happen again, but with the MotoG.

**Comment by jpailthorpe** [comment]
I also had this occur in the app yesterday on my iphone6splus. It is not device specific.

**Comment by mattwbenson** [comment]
unable to repro
