### ISSUE TITLE
UX: Debrief dialogue only half-visible on devices with phone-sized screens

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#213]
This is appearing on both the iPod Touch and the MotoG: 

![img_0036](https://cloud.githubusercontent.com/assets/12397944/25535578/93b47410-2c05-11e7-866b-98acc26711f9.PNG)

**Comment by esalling23** [comment]
removed bottom bar for this fix

**Comment by mattwbenson** [comment]
The text still lows a bit unusually low, but it is all visible now.
