### ISSUE TITLE
UX: APP: iPod Touch: Player names/roles losing formatting in modals

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#214]
iPod Touch:

![img_0037](https://cloud.githubusercontent.com/assets/12397944/25536598/6cc445c0-2c09-11e7-9cbc-98bbf7cc1224.PNG)

**Comment by jpailthorpe** [comment]
This has to do with a padding-left set at 12% on the innner-modal . inner .player-box. disabaling this fixes this problem.


![screen shot 2017-05-01 at 5 53 49 pm](https://cloud.githubusercontent.com/assets/10051544/25596504/70e2d6ea-2e97-11e7-8b9a-5c6db423a063.png)

![screen shot 2017-05-01 at 5 53 42 pm](https://cloud.githubusercontent.com/assets/10051544/25596514/7acb7ffe-2e97-11e7-847f-f2c92c3cb071.png)
