### ISSUE TITLE
UX: APP: iPod Touch: Decider "Next" button displaying outside speech bubble

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#215]
iPod Touch:

![img_0038](https://cloud.githubusercontent.com/assets/12397944/25536699/bdbf38ae-2c09-11e7-95d1-a377a955110e.PNG)

**Comment by jpailthorpe** [comment]
Saw this happening even with the correct dialog text css, so must be something else.

**Comment by esalling23** [comment]
This was working locally yesterday but appears to be acting up today on the app - moving to backlog

**Comment by jpailthorpe** [comment]
occuring again on iphone device. 
![screen shot 2017-05-05 at 6 56 52 pm](https://cloud.githubusercontent.com/assets/10051544/25767104/bb505038-31c4-11e7-827a-fc7f78d95c9e.png)

**Comment by jpailthorpe** [comment]
lets fix #278 first to see if it fixes this problem
