### ISSUE TITLE
UX: Lobby: Spaces in player names forces a return when they display in lobby

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#223]
This was on the iPod Touch, but it appears like this on all devices: 

![img_0039](https://cloud.githubusercontent.com/assets/12397944/25538626/77bdef96-2c11-11e7-9fe0-31ae7f333e94.PNG)

**Comment by jpailthorpe** [comment]
wacky! def. need to make sure names are never more than one line

**Comment by jpailthorpe** [comment]
solution is to not allow players to enter spaces in their name

**Comment by mattwbenson** [comment]
Still an issue in current build

![img_0040](https://cloud.githubusercontent.com/assets/12397944/25754316/b9ac19fc-318c-11e7-825e-a5d53916578c.PNG)

**Comment by esalling23** [comment]
@mattwbenson are you able to enter spaces then?
