### ISSUE TITLE
Pitch: Player name appearing in timer component on player screen who is pitching, creating weird double content

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#225]
The player who is pitching should only see the round question, not their own name. Right now it displays both in the same space, creating a weird overlay effect.

**Comment by esalling23** [comment]
@jpailthorpe Is this no longer an issue? We just talked and the question should not appear in the pitch phase

**Comment by jpailthorpe** [comment]
I think i went back and forth on this tbh. mockups are player names in pitch phase so thats good for now.
