### ISSUE TITLE
Instruction(actionbox-subheader) should be 14px NOT 16px

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#232]
This is why the text is breaking into three lines in different places. 

![screen shot 2017-05-01 at 5 27 17 pm](https://cloud.githubusercontent.com/assets/10051544/25595671/91513e02-2e93-11e7-9de8-56f3bde6b0b9.png)

![screen shot 2017-05-01 at 5 27 25 pm](https://cloud.githubusercontent.com/assets/10051544/25595676/96a5be8c-2e93-11e7-8460-607bbd488a2e.png)

**Comment by jpailthorpe** [comment]
also needs demibold font fam applied Fyi!

**Comment by jpailthorpe** [comment]
This is still not accurate. I noticed that there is no tags and the subheader content is just living in an unstyled div. 

needs to be 14px + demibold font fam. 
![screen shot 2017-05-03 at 11 33 23 am](https://cloud.githubusercontent.com/assets/10051544/25668399/92855832-2ff4-11e7-81e7-ce39804779de.png)
![screen shot 2017-05-03 at 11 33 30 am](https://cloud.githubusercontent.com/assets/10051544/25668400/92875ad8-2ff4-11e7-8056-f39cbdeb59ad.png)

**Comment by esalling23** [comment]
just committed a fix for this - will be fixed in next build

**Comment by mattwbenson** [comment]
The font-size is correct, but demibold family still needs to be applied.
