### ISSUE TITLE
actionbox-header: remove font-weight property from header title in instruction h1

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#235]
The font weight 700 is still being applied to the text with bold. This is causing unintentional linebreaks, and pushing content. 

<img width="727" alt="screen shot 2017-05-01 at 6 58 41 pm" src="https://cloud.githubusercontent.com/assets/10051544/25598020/5ed315d8-2ea0-11e7-84dd-54dfab47226a.png">

**Comment by esalling23** [comment]
@jpailthorpe did you mean the line-height which is commented out in the console?

**Comment by jpailthorpe** [comment]
no the weight (sorry that was me doing other things). The font weight shouldn't be set since it is pulling the actual font family bold. adding weight onto bold creates like a double bold
