### ISSUE TITLE
Global: decider screen showing role card button. When opened, blank content and no way to close breaks game

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#236]
Though a refresh on the dev tools or a reconnect by another player will sometimes reset the box, this causes a hard UX problem. need to remove the role card from appearing on decider screen 

(this was introduced sometime today fyi @johnnycrich )

**Comment by esalling23** [comment]
@johnnycrich @jpailthorpe I'm not able to reproduce this - the decider never has a role card button from what I see locally and on QA - is this still an issue?

**Comment by johnnycrich** [comment]
@jpailthorpe I also cannot repro. Did you see this immediately or only after round 1.

**Comment by jpailthorpe** [comment]
I might have gotten this after a reconnect on the decider side.

**Comment by mattwbenson** [comment]
I'm unable to reproduce

**Comment by jpailthorpe** [comment]
good enough for me! lets keep an eye on this in case it happens again.
