### ISSUE TITLE
Instructions: Instructions margin is set at 4px on player side compared to decider. Should be 16px across the board

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#243]
The margin bottom between the action box/instructions and the content(timer or dialog box) is set at 4px margin on player side screens. it should be  set to 16px margin. Originally this was 8px, but now that text should fit only on two lines (and there is more screen real estate height wise with the app) it allows us to give a little bit more room. 

I noticed there are some css elements that are possibly only being attributed to the player versus the decider. this makes sense for some elements, but is very rare and edge case. It might have been leftover code from previous designs/layouts. 

![screen shot 2017-05-03 at 11 47 00 am](https://cloud.githubusercontent.com/assets/10051544/25668991/4e376da8-2ff6-11e7-9f51-f5f2ae81748d.png)
![screen shot 2017-05-03 at 11 47 16 am](https://cloud.githubusercontent.com/assets/10051544/25668990/4e31b854-2ff6-11e7-88b9-dfbc67e116f5.png)

**Comment by esalling23** [comment]
@jpailthorpe I made this change but this is causing timer/speech bubble overlap on small screens.

**Comment by jpailthorpe** [comment]
Hmm. Mustn't be other code moving things into each other. Either way, these screenshots are on the smallest device. Remember we are not worrying about mobile phone browser play any longer, so if these two components are running into each other we have more leeway for height.
