### ISSUE TITLE
background logo allows for scrolling

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/at-stake-v3#246]
![img_0014](https://cloud.githubusercontent.com/assets/11821504/25669891/00cdccee-2ff9-11e7-9399-678b1e707e0d.PNG)

**Comment by jpailthorpe** [comment]
<img width="868" alt="screen shot 2017-05-05 at 6 45 12 pm" src="https://cloud.githubusercontent.com/assets/10051544/25766823/0174b72c-31c3-11e7-9241-1fa44490301d.png">

**Comment by mattwbenson** [comment]
Not possible to scroll on phone-sized screens, but it's still possible to scroll horizontally on tablet-sized devices.

**Comment by esalling23** [comment]
@jpailthorpe is scrolling horizontally an issue?
