### ISSUE TITLE
UX: Galaxy note2 displays "Seconds Left" text displaying outside timer circle

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#248]
![screenshot_2017-05-03-14-20-04](https://cloud.githubusercontent.com/assets/12397944/25675295/f55ecd8c-300b-11e7-9af9-45bb847a25b0.png)

This is displaying like this during all timers in all phases on the galaxy note 2.

**Comment by mattwbenson** [comment]
This is the only device that displays like this--other android devices are displaying the timer correctly.

**Comment by jpailthorpe** [comment]
We are currently investigating this to rule out some things.

**Comment by jpailthorpe** [comment]
this is actually occurring on both android devices (galaxy 3 + note 2). This might have something to do with the android native browser. Either way, I played through the entire game with both of these devices, and this is the only occurrence of weirdness I could find. I'm going to keep this open, but I don't want to try and fix this issue right now (unless we find this is not an android browser device specific problem and is simply a quick css fix).

**Comment by jpailthorpe** [comment]
![img_7298](https://cloud.githubusercontent.com/assets/10051544/25715847/f37d044c-30ca-11e7-94a6-eda4f13da011.JPG)

**Comment by jpailthorpe** [comment]
Verified that this is not occuring on more recent Samsung devices, and that this is not anything to do with screensize. There is something funky with the android native browser (which is what the app loads up) on older Samsung specific devices (the note 2 and galaxy s3, for example). There might be something with the specific css code we are using that this browser doesn't support. Either way, it is such a hyper edge case and the only thing that is happening on this device. game is still playable.
