### ISSUE TITLE
Logo image getting cut-off on bottom in modals

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#253]
This was on iPod touch, but it displays like this on all devices:
![img_0163](https://cloud.githubusercontent.com/assets/12397944/25709092/597a04c6-30b6-11e7-923f-86b68bdff982.PNG)

**Comment by jpailthorpe** [comment]
this is intentional, but shouldnt cause the visible overlap as referenced in #249

**Comment by jpailthorpe** [comment]
https://zpl.io/1A92AM

**Comment by jpailthorpe** [comment]
I exported the assets again with transparency around the box shadow in case you need them. they are in this folder. they are 50x51 pixels

https://drive.google.com/open?id=0B2iJJeD7RJtgdTdFMHNXWnFKN0U
