### ISSUE TITLE
UX: Leaderboard background obscuring phase-bar text on large phone+ sized screens

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#256]
This is on iPad, but the "score" text is concealed on basically every test device except the iPod touch.
![img_0037 2](https://cloud.githubusercontent.com/assets/12397944/25710988/d88edff2-30bb-11e7-83b4-659ba4086222.PNG)

**Comment by jpailthorpe** [comment]
ref #210 since this is related and most likely will be fixed around the same time.

**Comment by esalling23** [comment]
@mattwbenson where are you seeing this still occuring

**Comment by mattwbenson** [comment]
I've still been seeing it on all devices
