### ISSUE TITLE
PlayerDialogbox: ON desktop, all players are recieving the next button in their dialog boxes. Clicking on it breaks the game

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#257]
Not happening on devices. with the app. Seemingly only happening on browsers playing in desktop mode. Playing with devtools on in browser still shows the next buttons, so it isn't a screen size thing either. 

<img width="1434" alt="screen shot 2017-05-04 at 12 46 59 pm" src="https://cloud.githubusercontent.com/assets/10051544/25715284/0a414d3e-30c9-11e7-8184-899927cdd8d3.png">

**Comment by johnnycrich** [comment]
Cannot repro.
