### ISSUE TITLE
UX: Role card contents getting forced to bottom-left of layout, contents display but look cut-off

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#264]
This is on iPad, but this formatting is happening on all devices:

![img_0038 2](https://cloud.githubusercontent.com/assets/12397944/25752930/cb4d57f2-3187-11e7-8f9c-8edf6f311139.PNG)

**Comment by jpailthorpe** [comment]
I also noticed that it would be best to make sure the white height container space extends past the agenda item bullets. Now that we have more screen space, we don't have to worry about it getting cut off.

**Comment by jpailthorpe** [comment]
this is fixed now that new modal function works like menu screen
