### ISSUE TITLE
Auto-complete/next-word feature allows user to bypass ban on spaces in names

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#269]
Connected to #223 , players are able to get around the block on space-characters in names by using the autocomplete/next-word feature on both iOS and android.

**Comment by esalling23** [comment]
@mattwbenson please test this with the next build - I was able to get autocomplete to stop showing up on Chrome but autofill for contacts is still appearing on Safari. Since the app is wrapping Safari this may still be a problem.
