### ISSUE TITLE
remove #gamecontent.isMobile padding-top 10px 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#278]
Now that we are playing in app and not in browser, we can remove this padding element. 
![screen shot 2017-05-05 at 3 49 36 pm](https://cloud.githubusercontent.com/assets/10051544/25761919/92c26328-31aa-11e7-8675-3eed6c8581b5.png)

![screen shot 2017-05-05 at 3 50 57 pm](https://cloud.githubusercontent.com/assets/10051544/25761945/ac588fd8-31aa-11e7-89e3-ac206f45a016.png)
![screen shot 2017-05-05 at 3 50 53 pm](https://cloud.githubusercontent.com/assets/10051544/25761950/b3f209f4-31aa-11e7-8b4d-50bd044518d2.png)

**Comment by esalling23** [comment]
@jpailthorpe this will cause the instructions to overlap the phase bar text

**Comment by jpailthorpe** [comment]
on iphone 5 this text:
`

@media (max-width: 321px)
staging.css:1
body #gameContent.isMobile:not(.isDevice) {
    /* padding-top: 0; */`

is still overiding the 40px padding set in #gamecontent. just need to remove this (another leftover from our dumb dumb browser playing dayz)

**Comment by jpailthorpe** [comment]
I think this is being placed on a lot of elements across the app. Lets try to remove this
