### ISSUE TITLE
TimerComponent: Add "countdown" to timer so players better understand that time is about to start

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#29]
This is mentioned in @jpailthorpe 's notes, but players don't seem to get much forewarning before they start brainstorming/pitching/whatever. Whenever the decider presses "start timer" it should initiate a countdown from 3 2 1: go! and then start the 60 seconds. This, emphasized with animation, will really help players grock whats going on and to pay attention. I would even suggest having a full block of number either either the modal or just in that area of variable content.

**Comment by jpailthorpe** [comment]
would love to do this and will plan to make mocks to support, but unfortunately out of scope for this iteration :( :( :( :(
