### ISSUE TITLE
Lobby: When trying to join or start a new game,  if user clicks button to start game before animation loads can sometimes freeze game

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#302]
This happened for Eric. I know we already fixed something along these lines, but he had to force quit his game in order to get the buttons to respond again. Not sure. I tried to reproduce but I couldn't. Might be something to try and reproduce by just trying different things to see if we can trigger a freeze.

This needs to be tested on a live game (not local). 

 If not, we move this issue into known bugs pipeline and comment. If we can figure out what is triggering this action, if you can't figure it out @esalling23 just reassign to johnny and give some info.

**Comment by esalling23** [comment]
@jpailthorpe can we clarify for testing - was this the "start new game" button that leads to the lobby screen with the game code, OR was this the "play!" button on the lobby screen with the game code that leads to the tutorial option screen?

**Comment by jpailthorpe** [comment]
this screen: 

![intro_2_joinornewchoice](https://cloud.githubusercontent.com/assets/10051544/25868653/76ee2398-34cb-11e7-941a-d799551728d7.png)

**Comment by esalling23** [comment]
cannot reproduce
