### ISSUE TITLE
Round2: The first screen of round 2 is a bit confusing because it doesn't contextualize the shift to the new decider

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#306]

**Comment by esalling23** [comment]
added a new dialogue box for text explaining who is the decider. this only appears in rounds 2 or 3

**Comment by jpailthorpe** [comment]
I think this really needs to be a modal. It makes sense since it will draw attention to the players that the round has shifted and new things are happening. This was the biggest problem from the playtest: that players didn't understand that they were already dumped into the meet phase. 

This design helps give players
1. context that the round is changing. 
2. what round it is 
3. who the new decider of the round is
4. reinforces that players will receive a new role and to show them at a glance what those roles are
5. reshow scores up to this point. 

Player order does not matter, except that the new decider should always be in the first position. 

this modal should be timed like the others and set with its own value in keystone. Note that the modal is centered like the others. 

https://zpl.io/Z1s9R2e

**Comment by jpailthorpe** [comment]
![meet_0_round2 3 modal](https://cloud.githubusercontent.com/assets/10051544/25866551/cd6dacfe-34c4-11e7-8f1b-178324191a2b.png)
