### ISSUE TITLE
Small screens squish stages bar [iPod tested]

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/at-stake-v3#31]
![img_0010](https://cloud.githubusercontent.com/assets/11821504/24271330/2ae27004-0fef-11e7-8245-25ff5f048138.PNG)

**Comment by jpailthorpe** [comment]
just like #35 #37 #44 , once screens have been updated with new components and layouts lets confirm these have been fixed. If these problems still persist even with new designs, please assign me and explain why so I can come up with a solution.

**Comment by esalling23** [comment]
Unable to reproduce - potentially already fixed but not putting in "review" until final assets are integrated
