### ISSUE TITLE
Decide: Design update to agenda item modals 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#310]
This is refering to not showing the player the player names when a decider is selecting their agenda items.

**Comment by esalling23** [comment]
Names have been removed from decider screen text - waiting on redesign for removing player boxes on the player version of this screen

**Comment by jpailthorpe** [comment]
@esalling23 what do you mean by decider screen? The decider screen didn't have the player names on them. Just want to make sure we didn't remove something else! 

https://zpl.io/anA5e

**Comment by jpailthorpe** [comment]
New agenda item modals for decider and player in zepplin: 
![components_17_playeragendaselectionmodal 2](https://cloud.githubusercontent.com/assets/10051544/25868324/521a3d00-34ca-11e7-9d7e-78e714c931ed.png)
![components_16_decideragendachoicebox](https://cloud.githubusercontent.com/assets/10051544/25868325/521c2390-34ca-11e7-93d4-fd5345070b8b.png)

**Comment by esalling23** [comment]
@jpailthorpe I meant the player screen text - my bad!
