### ISSUE TITLE
UX (minor): Player turnover in lobby can leave all players with same icon image

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#317]
This was only after a bit of work to get to this state, but basically, on most attempts, if Player A joins the game after the Decider starts a lobby, then Player B joins, and then Player A disconnects and re-joins the game (appearing in the lobby below Player B), Player A will end up with the same player icon as Player B. This can be reproduced for all non-decider players in the lobby:

![img_0018](https://cloud.githubusercontent.com/assets/12397944/25905126/251a467e-356f-11e7-808d-f32d2bad640d.PNG)

**Comment by jpailthorpe** [comment]
_from a duplicate issue_

I was able to do this on the iPad 4 after having it join a lobby as the second player. Once I had added three other players to the game, I had the iPad leave the game, and then rejoin:

![img_0091](https://cloud.githubusercontent.com/assets/12397944/25048265/7b644edc-2109-11e7-98b7-686ca4b68a8e.PNG)
