### ISSUE TITLE
UX: New round modal cuts off on devices with short screens

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#318]
This is on iPod touch:
![img_0019](https://cloud.githubusercontent.com/assets/12397944/25906935/003f8792-3574-11e7-9f2f-e4ee07c067d3.PNG)

**Comment by jpailthorpe** [comment]
looks like its due to the player boxes having too much padding between them:

![meet_0_round2 3 modal 2](https://cloud.githubusercontent.com/assets/10051544/25968869/e76e566a-3660-11e7-80fe-9a7a7e3663ab.png)

**Comment by jpailthorpe** [comment]
also possibly left/right margins on text element since its pushing into four lines?
