### ISSUE TITLE
BottomBar: Update menu button with new icon, replace role card icon with old menu icon.

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#320]
Per aidan's suggestion, i changed the bottom bar icon. It should be in zep as a vector just like the other one. Note that the original menu icon (the at stake logo) is now the icon for the role card. It makes sense to use this instead of the blank head. 

![components_06_phasebar bottombar](https://cloud.githubusercontent.com/assets/10051544/25961167/554fdda8-3647-11e7-92ec-19e3fdc128bb.png)

**Comment by esalling23** [comment]
@jpailthorpe the 3-bar style menu bar is not downloadable in zeplin
