### ISSUE TITLE
Lobby: Update room code color to match mockup 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#321]
The L that was blue was really hard to read, so I changed it to purp. Aidan might suggest a dif. color before Friday though, so might change. Either way, I think this color is at least readable so better than it is now. 
![intro_3_gamelobby decider](https://cloud.githubusercontent.com/assets/10051544/25961861/beb770ce-3649-11e7-8708-1e5d656314ec.png)

**Comment by mattwbenson** [comment]
Light blue is still appearing.
