### ISSUE TITLE
Debrief not loading

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#333]
Once the final round has finished and the debrief starts, this is all that displays on all devices: 
![img_0043](https://cloud.githubusercontent.com/assets/12397944/26013280/a642879a-3725-11e7-8f41-265c89061a2f.PNG)

**Comment by johnnycrich** [comment]
Fixed by commit 195a2e7e2c2ed9f925c298f71729bf36557062b1.
