### ISSUE TITLE
QA_Component_bottombar: Role card and Menu icons missing

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/at-stake-v3#34]
<img width="457" alt="screen shot 2017-03-23 at 5 37 59 pm" src="https://cloud.githubusercontent.com/assets/11821504/24271433/8a25b152-0fef-11e7-86fc-764fa4aac963.png">

**Comment by jpailthorpe** [comment]
@esalling23 just pushed these to zep yesterday fyi

**Comment by jpailthorpe** [comment]
https://drive.google.com/open?id=0B2iJJeD7RJtgMldFRThaVnRSS1U

**Comment by jpailthorpe** [comment]
Still waiting on Aidan's svg icons for the buttons, but right now the shadows/text alignment and size can be adjusted to match mocks.
