### ISSUE TITLE
Small screens cut off "next" arrow on speech bubbles [iPod tested]

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/at-stake-v3#35]
![img_0013](https://cloud.githubusercontent.com/assets/11821504/24271603/2885a2c6-0ff0-11e7-9cc5-64a262e1e475.PNG)

**Comment by jpailthorpe** [comment]
just like #31 #37 #44 , once screens have been updated with new components and layouts lets confirm these have been fixed. If these problems still persist even with new designs, please assign me and explain why so I can come up with a solution.
