### ISSUE TITLE
App: Downloaded app needs more top padding to allow for time, device battery, etc.

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/at-stake-v3#36]
![img_0012](https://cloud.githubusercontent.com/assets/11821504/24271686/6a6bf316-0ff0-11e7-852e-478ec72354bc.PNG)

![img_0011](https://cloud.githubusercontent.com/assets/11821504/24271634/3ed34b6e-0ff0-11e7-8e20-9565acb60d7b.PNG)

**Comment by jpailthorpe** [comment]
because this is app version, we will wait until after playtest

**Comment by jpailthorpe** [comment]
many fixes and changes since this, so closing for now.
