### ISSUE TITLE
[iPod] Deck selection screen feels squished, slider dots are stretched

### ISSUE THREAD

**Issue by esalling23** [engagementgamelab/at-stake-v3#37]
![img_0011](https://cloud.githubusercontent.com/assets/11821504/24271666/5b5d7516-0ff0-11e7-8e73-d76d96bd6dcd.PNG)

**Comment by jpailthorpe** [comment]
just like #35 #31 #44 , once screens have been updated with new components and layouts lets confirm these have been fixed. If these problems still persist even with new designs, please assign me and explain why so I can come up with a solution.
