### ISSUE TITLE
UX: Some Game setup buttons hard to notice

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#38]
The "next" button after deck selection is very hard to notice.
![screen shot 2017-03-24 at 10 44 00 am](https://cloud.githubusercontent.com/assets/12397944/24299245/eb1c2902-107e-11e7-9ea4-6f5fd633e928.png)

**Comment by mattwbenson** [comment]
The lack of contrast in the room code also makes it hard to read

![screen shot 2017-03-24 at 10 46 11 am](https://cloud.githubusercontent.com/assets/12397944/24299468/aab349d0-107f-11e7-8dd4-9a1d84eea426.png)

**Comment by mattwbenson** [comment]
This is for room code entry on the iPad mini--the directions are impossible to read
![img_0028](https://cloud.githubusercontent.com/assets/12397944/24299855/e7312160-1080-11e7-8170-1ddd7466a2e1.PNG)

**Comment by jpailthorpe** [comment]
I think this has more to do with the way the mobile device is appearing on desktops. This is something we will need to address, but after next week.
