### ISSUE TITLE
Global: Game copy is insanely difficult to read

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#40]
In all stages of the game, from setup to actual play, any copy that isn't "quoted in large central blocks" looks like it's about 6-8pt in size, on all devices (though on safari/apple devices, color management leads to less contrast and makes it even more difficult to read). People with color blindness or poor eyesight may genuinely be unable to read game instructions or text on role cards.

**Comment by jpailthorpe** [comment]
make sure you reference new zeppelin boards from last week. There is never a fontsize that should be less than 12px, with 16 as the base size. Also fun fact: you can hold alt on the keyboard when viewing an object in zeppelin to see percentage values instead of pixel values.  

here is the em conversion chart if its easier
http://pxtoem.com/

**Comment by esalling23** [comment]
@mattwbenson please include screenshots for anything that include css or formatting issues in the future! 
@jordan it doesn't look like there are any fonts set to anything smaller than 12px, so if the fonts are still too small to read we should pick a larger size for them

**Comment by mattwbenson** [comment]
Text is still looking difficult to read, partially because of the text color but also the small size: 
![screen shot 2017-03-31 at 10 08 08 am](https://cloud.githubusercontent.com/assets/12397944/24553992/14730bba-15fa-11e7-8dc3-472227ad56f5.png)

**Comment by jpailthorpe** [comment]
If it is 12px, it is accurate to mocks. This particular text is helper text and is intended to only be read if needed. It is the equivalent to rollovers, if that helps better understand the context. 

that said, don't disagree it is small or could use some massaging, but putting this on the backburner for now.

**Comment by mattwbenson** [comment]
This was resolved in the last build I played.
