### ISSUE TITLE
Login/Lobby: Create/Join game pages can be broken by navigating between them

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#42]
Once a player has chosen their name, they can force both the "new game" and "join game" pages to load by selecting one, using the back button, and then selecting the other. This was on chrome for desktop. 
![screen shot 2017-03-24 at 11 42 29 am](https://cloud.githubusercontent.com/assets/12397944/24301889/25f026de-1087-11e7-8f11-c5e0e385673f.png)

**Comment by mattwbenson** [comment]
This occurs on the app for iOS as well.

**Comment by mattwbenson** [comment]
This error will also occur if the user selects the same option twice in a row--the correct page will load, then flicker as though it has been re-loaded, and then disappears completely.

**Comment by jpailthorpe** [comment]
hmm this sounds pretty serious. Lets investigate
