### ISSUE TITLE
Login/lobby: Add copy line of instructions as seen in mockup to template screen

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#43]
It would be helpful to have some copy explaining that players can swipe on the deck to change it--I didn't realize this was possible until I did it by accident.

**Comment by jpailthorpe** [comment]
yes, copy line should be in there. It was taken out in the psd mockups but it is important to keep in. 
<img width="407" alt="screen shot 2017-03-27 at 12 45 53 pm" src="https://cloud.githubusercontent.com/assets/10051544/24367638/6186ca0c-12eb-11e7-9cb7-324bfcc0fd83.png">

**Comment by jpailthorpe** [comment]
fixed
