### ISSUE TITLE
UX: Progress bar getting scrunched on phones

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#44]
(Galaxy S6)
![screenshot_20170324-115508](https://cloud.githubusercontent.com/assets/12397944/24302450/0db55bbe-1089-11e7-86fb-e1ce62ea4252.png)

**Comment by jpailthorpe** [comment]
just like #35 #37 #31 , once screens have been updated with new components and layouts lets confirm these have been fixed. If these problems still persist even with new designs, please assign me and explain why so I can come up with a solution.

**Comment by esalling23** [comment]
duplicate. closing.
