### ISSUE TITLE
Pitch/Deliberate: Inactivity at end of Pitch round can freeze game without way forward

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#46]
If the host screen isn't active during the transition between the "pitch" and "deliberate" rounds, the game will become broken, with a timer at 0 appearing on all screens, and no buttons to progress to the next round.

**Comment by mattwbenson** [comment]
Refreshing the host device in this state will create a game window that only has the progress bar, menu  and role-card buttons, and coin values.

**Comment by johnnycrich** [comment]
@mattwbenson Can you clarify what you mean by the "host" (decider?) not being "active" (screen is off?).

**Comment by mattwbenson** [comment]
Sorry, yes, the host is the decider, but I mean inactive just in that the
browser window was either minimized or another tab had focus.

**Comment by mattwbenson** [comment]
Just had this occur on a game with three desktop players, one ipad, and one samsung tablet. Only one of the desktop players (not the decider) had an inactive window, and froze the game between the pitch and decider rounds. The screen that had been inactive just continues to count down the timer into negative values: 

![screen shot 2017-03-31 at 11 42 27 am](https://cloud.githubusercontent.com/assets/12397944/24557821/25a00e3a-1607-11e7-911b-e5a22c2b49f2.png)

**Comment by jpailthorpe** [comment]
verify that this is fixed

**Comment by jpailthorpe** [comment]
testtest tes test ts st

**Comment by mattwbenson** [comment]
Can't reproduce
