### ISSUE TITLE
Gamebreaking: If player buys additional time in pitch round, game breaks

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#47]
During the pitch round, if any player chooses to buy additional time to speak, the additional time will be added to the timer and count down, but afterwards, the "next player" button will never appear on the host screen, only the timer at 0. Refreshing the host device in this state will return only the standard game UI, without any other elements.

**Comment by jpailthorpe** [comment]
#46 #52 #28
