### ISSUE TITLE
Reconnection: If multiple people get disconnected, the game doesn't know how to handle it.

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#49]
I had a session where the host player was disconnected, triggering the DC error message, and shortly afterwards I accidentally refreshed the device of Player 1. This removed the error message for about a minute, after which the error message returned, but asking for Player 1 to reconnect, rather than the host player.

**Comment by jpailthorpe** [comment]
This is linked to #46 #41 #47 #30

**Comment by mattwbenson** [comment]
Just had this occur after trying to disconnect and reconnect with multiple screens at once:

![screen shot 2017-04-07 at 12 23 12 pm](https://cloud.githubusercontent.com/assets/12397944/24809386/55c7999e-1b8d-11e7-861c-22f3ed8c2ce6.png)

The decider clicked Back to go to the landing page and tried to return to the game via Forward. At the same time, Desktop 2 was continuously refreshing the game page. The game was in the middle of the Pitch Round.

**Comment by mattwbenson** [comment]
In the above case, after logging the issue, I made the middle screen (the one deciding whether to pay coins) go Back and then Forward again, after which it had the same "undefined" screen as the first screen.

**Comment by jpailthorpe** [comment]
Just moving to done because it feels a bit hard to reinvestigate.
