### ISSUE TITLE
Reconnection: Pressing home button disconnects device from game

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#51]
I've only noticed this issue so far on my Galaxy S6, but any time I press the home button (not exiting the app but just minimizing it) the device becomes immediately disconnected from the session and can't rejoin.

**Comment by jpailthorpe** [comment]
I found this as well with my iphone, but I can't remember if it was with the app or with the web browser. Was it the app on your andoird (with hockey app) @mattwbenson ?

**Comment by mattwbenson** [comment]
No, I was on chrome.

**Comment by jpailthorpe** [comment]
gotcha. So If there is no option to rejoin, I am curious if the other players are getting the "wait for some player to return" error message, and if so, why the player who minimized the app is not able to rejoin upon opening again.

**Comment by jpailthorpe** [comment]
This does not happen in current build with iphone6s on chrome. I tested this being a player and as the host, and just hitting the home button, even after multiple minutes and opening multiple other apps and tabs in my browser didn't interrupt the game nor did it give any disconnect errors. 

Need to test again on android before confirming fixed.
