### ISSUE TITLE
PitchPhase: Final player in pitch round can't buy additional time

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#52]
When the final player is pitching during the "pitch round", once their timer ends, the entire game moves on to the next round. The player sees the dialogue box offering the opportunity to buy additional time, but it displays on top of the first screen in the "deliberate" round.

**Comment by jpailthorpe** [comment]
Related to #47

**Comment by johnnycrich** [comment]
I have not been able to reproduce this today.
