### ISSUE TITLE
Login/lobby: Error message staying visible across templates unless tapped/clicked to clear. Should be set to disappear automatically after a few seconds

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#58]
![error message styaing visible across templates unless tapped clicked to clear should be set to disappear automatically after a few seconds](https://cloud.githubusercontent.com/assets/10051544/24381854/96b5cc52-1320-11e7-97f7-a0bb38c47070.png)

**Comment by mattwbenson** [comment]
This issue has been fixed for iOS devices and modern android/chrome setups, but it's still occurring on the lab's older samsung tablet. Johnny advises to move back to backlog for now.

**Comment by jpailthorpe** [comment]
Please check on iphone and desktop and android devices to see if this is still occuring. Please also give us some subjective idea of how much of an impact this is (ie. is it just annoying? break layout/function?)
