### ISSUE TITLE
MeetPhase: Bottom bar not appearing on all player screens, only decider screen. gameplay breaking 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#62]
The bottom bar is not appearing on player screens using chrome. This doesn't break the game programmatically, but because the player can't see their role/hidden agenda, there is no way to introduce each other. This needs to be resolved before anything else in order for the game to be playable. 

Here is the player view: 
![meet- bottom bar not appearing on player screens only decider screen](https://cloud.githubusercontent.com/assets/10051544/24462618/6ce4905e-1472-11e7-9cf9-89f836fbd1df.png)

Here is the decider view: 
![meetphase bottom bar decider view](https://cloud.githubusercontent.com/assets/10051544/24462742/c10ad76a-1472-11e7-932d-ff1e8103bdef.png)

**Comment by johnnycrich** [comment]
This should be fixed as of 400afc06b8d102a55590adb22e279c57c8fdc0d6
