### ISSUE TITLE
Rolecard/menu(?): when a player refreshes their screen, after they are back in the game, the role card button is not longer clickable

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#65]
The pointer still reads as a clickable element, but the rolecard does not appear to open. Even if refreshing again, and moving on to another screen (advancing the game) does not fix this problem. This happened in chrome on desktop, not sure if just related to desktop. Needs to be tested on phone.

**Comment by jpailthorpe** [comment]
please verify this is still a problem using instructions above

**Comment by mattwbenson** [comment]
Still seeing this as of 4/14 on all of the devices I'm using, tagging them in this issue.
