### ISSUE TITLE
PlayerView: Coin amounts (both player and coin pot) not appearing on player views, but appearing on decider.

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#66]
desktop, chrome. This screen is in the brainstorm phase, but it is true from the beginning of the game. 
I am not sure if amounts are begin pulled correctly from the cms. Labels are a bit confusing (since a player does not gain more coins each round automatically...which is how it is labeled in the cms. I left this at zero, which might be why this is happening). If this simply means the coin amount players are STARTING with, that might solve it. Lets investigate the cms setup and make sure it is correctly assigning and pushing coin values. Once I have this confirmed, I will change the values and can test again. 

**This is the player screen**
![screen shot 2017-03-29 at 2 54 33 pm](https://cloud.githubusercontent.com/assets/10051544/24471310/b87a007c-148f-11e7-8ca7-8c5076c4d044.png)

**This is the decider screen**
![screen shot 2017-03-29 at 2 55 19 pm](https://cloud.githubusercontent.com/assets/10051544/24471323/c6d259f8-148f-11e7-96df-37635faafad9.png)

**Comment by johnnycrich** [comment]
@jpailthorpe So for sure the decider and player do not automatically get a bonus amount of coins as round 2 and 3 start? This was present in the unity version.

**Comment by jpailthorpe** [comment]
I would like to test not getting more coins, and see how it plays out with areal life test through 3 rounds. Reason being, if player's get an auto "refresh" of coins at the start of each round it breaks the rationale for players to want to get more coins. Therefore, if a player uses all these coins and ends up in a situation in which they have less than 50 coins they simply cannot buy more time. This puts them at a disadvantage, yet at the same time, could drive motivation to acquire more coins in the next round. This is from a game design rationale. 

In addition, a player would have to realistically not acquire any coins at all AND buy time 3 different times (since every player starts the game with 200 coins) for them to end up in a position where they can no longer buy time. This is absolutely possible, but my gut feeling is it will be rare, and players who do end up in this position might not be utilizing their coins/time strategically. 

After testing these assumptions, we can return to this to evaluate. I will make a note of this to add to my ux test questions though!
