### ISSUE TITLE
rolecard: Bio text is colored orange on desktop/chrome, only able to read when highlighted.

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#67]
![rolecard bio text color no highlight](https://cloud.githubusercontent.com/assets/10051544/24474968/6861b636-149c-11e7-9369-78de11392dd0.png)

![rolecard bio text color](https://cloud.githubusercontent.com/assets/10051544/24474973/6b842c2c-149c-11e7-92ec-3c15c98f43c2.png)

**Comment by esalling23** [comment]
If there is an image added to the role, then this should offset the text and have it instead be on top of the white background, and visible - @jpailthorpe did this role card have an image in keystone?

**Comment by mattwbenson** [comment]
Still seeing this (or not)

**Comment by esalling23** [comment]
This is due to content. This is not a bug.
