### ISSUE TITLE
Reconnection: When the host encounters a server crash, navigates to a different page, or even refreshes their page. they can't rejoin the game and other players are stuck

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#68]
on desktop 

I started a game with the screen on the left being the host/new game maker. Started the game and entered the phase. I went to facebook in the tab I was playing in. I then tried going back and instead got the screen on the left. This is the entry screen but with no name. 

Refreshing the page when I was at this point didn't do anything except bring me to this same screen. 
note that this is **not** happening when making the main tab inactive or changing windows) 

<img width="1550" alt="screen shot 2017-03-29 at 4 29 54 pm" src="https://cloud.githubusercontent.com/assets/10051544/24475338/886bee64-149d-11e7-93a9-ca1aa5b1f5b1.png">

**Comment by johnnycrich** [comment]
@jpailthorpe This is most likely fixed as a result of numerous other fixes last week. I cannot repro currently, pls try doing so,

**Comment by mattwbenson** [comment]
I just reproduced following the instructions above, the only difference is that after pressing back, the reconnection timer on the other player's screens disappeared.

**Comment by jpailthorpe** [comment]
Please review and verify

**Comment by jpailthorpe** [comment]
more info on this: 

Basically, anytime the decider refreshes the game (accidently or otherwise) the game is completely broken. This is because the decider is then sent to the lobby login screen, while the other players are stuck in a strange reconnection limbo. 

I am not sure there is any way around this, aside from making sure all players are also immediately kicked from the game as well when this happens. Otherwise, the players are confused as to why the decider can't rejoin, and therefore don't know what to do.

**Comment by johnnycrich** [comment]
I pushed a fix that resolved an issue where after the decider re-connected, their new web socket was not cached on the backend, preventing them from seeing new phases. This issue may have also caused what was described above. Pls try to repro.

**Comment by mattwbenson** [comment]
Tried refreshing/navigating to and from different pages, at a couple of different states, can't reproduce

**Comment by mattwbenson** [comment]
This has been re-occurring for me, but generally it's been in the second half of the round.

**Comment by jpailthorpe** [comment]
This original problem with the blank login screen + players not being booted to the login screen if the game is ended has been fixed. There are still some weird edge cases where the device will fall asleep (specifically on google chrome on iOS devices) or when the player intentionally turns the screen off,  which will disconnect a player from the game. There is no way around this unfortunately. This does not happen on Safari. 

Because this is an edge case, I am going to close this issue. I will write up a "known issue" document addresses these weird edge cases going forward.
