### ISSUE TITLE
LobbyScreen: small css tweaks to get closer to mock 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#69]
on iphone, this is what the loginlobby screen looks like: 

![qa atstakegame org-play iphone 5 1](https://cloud.githubusercontent.com/assets/10051544/24478758/134ee1ce-14aa-11e7-936b-7ae83fb3eb4a.png)

Changing the game content container to not having an additional 8px of padding on the right and left side (as well as the 40>20 px top padding) makes the screen closer to the mock. Also note that copy has changed in the new mock last week to be shorter and more succinct. 
![screen shot 2017-03-29 at 6 02 10 pm](https://cloud.githubusercontent.com/assets/10051544/24478795/45f482b4-14aa-11e7-9ede-f17ab53b4397.png)

**Comment by jpailthorpe** [comment]
also important to double check colors. I am not sure if a color picker was used, but it sometimes distorts readings based on your monitor settings, and can throw off from real colors. The real colors are all in zep (double checked this morning !)

**Comment by jpailthorpe** [comment]
also I just noticed this is different from the player version of the screen, so lets just make sure to note this when making fixes to this. 

Decider:

![screen shot 2017-03-29 at 6 12 48 pm](https://cloud.githubusercontent.com/assets/10051544/24479018/55e5c25e-14ab-11e7-90a7-1d1c3796e777.png)


player: 
![screen shot 2017-03-29 at 6 12 30 pm](https://cloud.githubusercontent.com/assets/10051544/24479006/4cbb7e08-14ab-11e7-8b71-5fd1379b6c01.png)

**Comment by mattwbenson** [comment]
Mockups in zeplin show slight difference in the UI and copy for the decider and the players in the game lobby--in current build, the two lobby screens are identical 

![screen shot 2017-04-07 at 12 39 54 pm](https://cloud.githubusercontent.com/assets/12397944/24810191/754904ea-1b8f-11e7-970f-fb13d553a24c.png)

**Comment by esalling23** [comment]
Made separate issue for back buttons, closing for copy change - tested as fixed.
