### ISSUE TITLE
UI elements/copy clipping each other on iPhones

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#72]
This is a screencap at iPhone 5 screen size, while the UI displays properly when the page first loads, if an error message appears, it disrupts the layout.
![screen shot 2017-03-31 at 11 13 37 am](https://cloud.githubusercontent.com/assets/12397944/24556873/d050a708-1603-11e7-9183-9d8d000d6e2e.png)

**Comment by mattwbenson** [comment]
On the same device, the deck cards load in this half-half state, and it's impossible to get them to "set" in a way that you can actually read an entire card without keeping your finger on it.

![img_0003](https://cloud.githubusercontent.com/assets/12397944/24555818/72ff490e-1600-11e7-9135-c8901874db22.PNG)

**Comment by mattwbenson** [comment]
This is the same behavior as above, but on the iPhone 5 rather than the 4. 
![screen shot 2017-03-31 at 11 20 01 am](https://cloud.githubusercontent.com/assets/12397944/24556958/12c6b3f2-1604-11e7-9985-f3bed30e1ee6.png)

**Comment by mattwbenson** [comment]
iPhone 5:
![screen shot 2017-03-31 at 12 01 28 pm](https://cloud.githubusercontent.com/assets/12397944/24558642/d7b9b4a2-1609-11e7-8f8f-74f70eb26f02.png)

**Comment by jpailthorpe** [comment]
I think a lot of this is fixed this week, but need to be QAed again to make sure. moving to backlog, just letting you know @esalling23

**Comment by esalling23** [comment]
@mattwbenson can you confirm that these are fixed/still happening?

**Comment by mattwbenson** [comment]
I've been only QAing desktop today so far for the next playtest, but I wasn't seeing this behavior on mobile in the last build I played?

**Comment by esalling23** [comment]
@mattwbenson awesome, if you can switch to mobile testing for a bit to confirm that, that'd be great. Moving to in progress until confirmed

**Comment by jpailthorpe** [comment]
after lots of latest pushes last week, lets retest this. make sure to test this on your device test set.

**Comment by jpailthorpe** [comment]
Though there are some layout problems still, the images referenced in this issue are all confirmed as fixed across our test device set. moving to done for now.
