### ISSUE TITLE
LandingPage: Integrate updated SVG assets for the landing page

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#73]
Highest priority are the three illustration assets in the middle of the page--the ear, the trophy, and the coins. The current assets are too low-res, and the colors wash out into neon green on older browsers without anti-aliasing.

**Comment by jpailthorpe** [comment]
@aidanrae adding these to you list in issue #56

**Comment by jpailthorpe** [comment]
these assets are in SVG format in the main assets folder on the drive now. We should have all things needed from aidan.

**Comment by jpailthorpe** [comment]
svg in landingpagefolder
