### ISSUE TITLE
Game allows more players than set in keystone, UI has no way to handle it

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#74]
Once players continue to join the game after the fifth one, they can join the lobby, they are just not assigned a player icon. Their names will continue to be added to the list, to the point that it will completely break formatting on smaller screens: 

![screen shot 2017-03-31 at 11 30 07 am](https://cloud.githubusercontent.com/assets/12397944/24557448/b56c5494-1605-11e7-8c2f-772011137fc1.png)

**Comment by jpailthorpe** [comment]
hahaha amazing. good catch!! Lets make sure this is connected to cms or if easier, hard limit at 5 players. game should never support more than 5.
