### ISSUE TITLE
Reconnection: Decider can't reconnect/refresh from error screen

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#75]
Related to issue #68 , but I had a game where the decider was disconnected, sending an error message to all devices, including the decider, that the decider needed to refresh/reconnect. Despite repeatedly refreshing the decider screen, it only reset the counter on the error message across all screens. Once I closed one of the (non-decider) screens, the error timer started counting irregularly, jumping up and down by several numbers at a time .

**Comment by jpailthorpe** [comment]
please try to recreate and verify this is  fixed :)

**Comment by jpailthorpe** [comment]
This is very close to #68. The timer jumping problems have not been seen since this issue was created. Therefore, moving this to done and keeping all dialog about decider refresh problem in #68
