### ISSUE TITLE
Gamebreaking: Decider isn't following game flow, jumps stages ahead without others

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#76]
This issue has a couple of different visible examples, but the most obvious is at the first screen of the game: 

![screen shot 2017-03-31 at 12 18 44 pm](https://cloud.githubusercontent.com/assets/12397944/24559297/36014f64-160c-11e7-9011-7bd593233bd6.png)

The decider starts in the Brainstorm stage, while all other players are still in "Meet." 

As the game progresses, there are also moments where the decider will have a dialogue appear multiple times at once, because the decider has jumped ahead to a future stage. 

![screen shot 2017-03-31 at 12 13 58 pm](https://cloud.githubusercontent.com/assets/12397944/24559172/bcaa2690-160b-11e7-8007-e381f1a23506.png)

When players are preparing for the brainstorm stage, the decider will get the "get ready" dialogue for the brainstorm stage, but then immediately afterward, the game will show the decider in the deliberate phase, and repeat a "get ready" dialogue (from that phase) while the game is still in the Brainstorm phase. 

![screen shot 2017-03-31 at 12 14 11 pm](https://cloud.githubusercontent.com/assets/12397944/24559183/c988742a-160b-11e7-9a45-10ccb06293d7.png)

**Comment by jpailthorpe** [comment]
Look like this is more specifically an issue with the Phase bar progress, and not the entire template. other screens are actually matching (the decider screen copy and the player screen copy are sometimes slightly different). 

Here is a link to current mockups in case you need to reference. https://scene.zeplin.io/project/58a352974ec334e848da2c60

**Comment by mattwbenson** [comment]
At least on my end, on the current build, there's literally no moment in the game where the decider and the other players appear to be in the same stage, regardless of the copy.

**Comment by mattwbenson** [comment]
See #78
