### ISSUE TITLE
UX: Name-entry page doesn't shorten long names, breaks formatting

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#77]
This is very minor, and it's mostly handled in other parts of the game where long names get shortened, but during game set-up, the full names will run on and break the layout.

![screen shot 2017-03-31 at 1 42 14 pm](https://cloud.githubusercontent.com/assets/12397944/24562211/037d7c6e-1618-11e7-8cce-afb73d1e22c9.png)

**Comment by jpailthorpe** [comment]
oh yes could catch. Designs are constructed to limit player names to 10 characters only. for now, lets implement that restriction. This for now also does not need to be a notification to players if they go over ten characters, only that when typing their name, the cursor stops inputting characters after ten.
