### ISSUE TITLE
Major UX: Phase progress bar broken, gives impression that players/rounds get skipped

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#78]
I started the game with three players on chrome desktop, Decider, Desktop 1, and Desktop 2. I made it to the start of the pitch phase without any issues. Desktop 1 got to pitch, and then chose not to buy any additional time. Then, the game's dialogue suggested that it was Desktop 2's turn to pitch, but the phase bar showed that the game had advanced to the next round, Deliberate, for all players. 
![screen shot 2017-04-04 at 11 01 05 am](https://cloud.githubusercontent.com/assets/12397944/24663764/d733bd46-1926-11e7-8869-5ff326733292.png)

After Desktop 2 finishes its pitch (with the phase bar still in "Deliberate"), the game's dialogue implies that the game is moving into the "Deliberate" stage, but the phase bar shows the game has advanced: 
![screen shot 2017-04-04 at 11 13 12 am](https://cloud.githubusercontent.com/assets/12397944/24664084/b85dc064-1927-11e7-950a-fb127722808a.png)

After the "deliberation" time has finished (with the phase bar still at "Decide"), the game appears to entirely skip the "decide" round (at least from a UX perspective), jumping straight to "score" while the decider chooses the winner.

**Comment by johnnycrich** [comment]
Should be resolved via 87d185cee2df306ce78dc0bcd23e477d043721eb.
