### ISSUE TITLE
Timer Button: The button under the timer has a state that makes it very hard to read.

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#80]
I think this is a quick fix and most likely from bootstrap. simply take out the background of the button. This is on desktop, but I have noticed this on phone as well. 

![screen shot 2017-04-04 at 8 33 12 pm](https://cloud.githubusercontent.com/assets/10051544/24685394/38d42ff0-197b-11e7-9923-ae4cd4a0ef83.png)

**Comment by jpailthorpe** [comment]
If this isn't happening on Desktop chrome, don't worry about it for now.

**Comment by johnnycrich** [comment]
Fixes as of 4/7.
