### ISSUE TITLE
Pitch-Gamebreaking(kinda): If a player buy time in pitch phase, the timer doesn't auotmatically start, making it zero,.

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#84]
played a game and decided to buy more time in pitch. after clicking yes, this is the screen: 

![screen shot 2017-04-04 at 8 36 41 pm](https://cloud.githubusercontent.com/assets/10051544/24685790/b9f21438-197d-11e7-9edf-04128e5b04e7.png)

Refreshing the game on the player screen brings back the modal for selecting to buy time. If i click buy time again, it still does the same thing. But I do have the option to say no thanks and continue on as usual with no problems. (unsure if my coins were still subtracted). 

Basially makes buying time not work. Possible reason is its waiting for the decider to start the timer? But the decider can't because the modal is still up.

**Comment by mattwbenson** [comment]
Just tried to buy more time in the pitch phase, the timer loaded at zero, and then all player screens had this error appear:

![screen shot 2017-04-07 at 10 56 38 am](https://cloud.githubusercontent.com/assets/12397944/24805861/fd3a8edc-1b80-11e7-81da-c8879a34b888.png)

**Comment by mattwbenson** [comment]
This was fixed in the latest branch merge
