### ISSUE TITLE
Analytics: Add G analytics to both QA and production 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#87]
Want to setup some metrics and goals for testing on Monday, so having the ability to track data throughout the experience on the G analytics dashboard will help align verbal and written feedback with hard metric data to complete the picture.

**Comment by jpailthorpe** [comment]
It would be great if we could also capture everyone's username in analytics so that we can tie survey to session data.

**Comment by johnnycrich** [comment]
This is now enabled on QA. In about a day we should start to see event data here: https://analytics.google.com/analytics/web/?authuser=2#report/content-event-overview/a64617433w143126477p147745353/

**Comment by jpailthorpe** [comment]
production? I think thats what we really need, especially for May 8th!

**Comment by johnnycrich** [comment]
@jpailthorpe Added analytics tracking for phase advance, joined game success, player reconnected, game started, game ended, became decider, coins added/removed. These will be on prod when next build is made and are on qa now.
