### ISSUE TITLE
LandingPage: device width's of less than 507px are showing are large white sidebar on the right side, making the entire site constrained. 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#9]
Must be a width/padding/or margin thing on a breakpoint.

**Comment by jpailthorpe** [comment]
![atstakegame org- iphone 5](https://cloud.githubusercontent.com/assets/10051544/23521050/65dbdd62-ff4b-11e6-82ad-ac0b9237c67b.png)

**Comment by mattwbenson** [comment]
Just an issue with bootstrap columns

**Comment by jpailthorpe** [comment]
awesome. just reopening to move to review. thanks!

**Comment by mattwbenson** [comment]
This seems to be an issue with the way the Sass is compiling media queries-- @johnnycrich is aware of the issue
