### ISSUE TITLE
PHASEBAR: DA FUGG 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#91]
LETS JUST USE THE CIRCLE STYLES WITHOUT THE IMAGES FOR NOW. 

this is in zep. 

Active circle: 40-40
inactive: 23-23

note that the distance between the inactive icons should be 23px, and that distance should always be proportional when operating under a larger width. 

<img width="620" alt="screen shot 2017-04-06 at 4 28 53 pm" src="https://cloud.githubusercontent.com/assets/10051544/24774226/2789d440-1ae6-11e7-9af8-d831ec6f5619.png">

**Comment by esalling23** [comment]
- [ ] add placeholder icons
- [ ] ensure text is centered
