### ISSUE TITLE
Major: Decks not visible during game setup on production

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#92]
This is on chrome desktop on Production during game setup--the deck selection screen loads without any visible decks.
![screen shot 2017-04-07 at 10 26 50 am](https://cloud.githubusercontent.com/assets/12397944/24804679/35b364fe-1b7d-11e7-89ac-f6676b5c685a.png)

**Comment by mattwbenson** [comment]
It is impossible to proceed from this point--selecting "next" only generates this error: 
![screen shot 2017-04-07 at 10 31 35 am](https://cloud.githubusercontent.com/assets/12397944/24804717/6da294e8-1b7d-11e7-8cf6-693043f49d06.png)

**Comment by jpailthorpe** [comment]
this is because there is no content in keystone. Database needs to be merged, referenced in #90
