### ISSUE TITLE
Gamebreaking: Timer, progression buttons disappear in middle of Double down phase

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#96]
Game had four players all on Chrome desktop. The game had proceeded normally with Desktop 1 buying additional pitch time during that round. Once the game advanced to Doubledown, Desktop 2 was the first player given a chance to speak and then buy more time. Desktop 2 bought additional time once, but then ended its turn. Once it declined to buy additional time, the player screens cleared except for the base UI, and the decider screen lost the timer and progression buttons:

![screen shot 2017-04-07 at 11 27 37 am](https://cloud.githubusercontent.com/assets/12397944/24807309/b2a33dd8-1b85-11e7-9014-1c9945b5fdb1.png)

**Comment by jpailthorpe** [comment]
@mattwbenson I assume you meant double down, not deliberation.

**Comment by mattwbenson** [comment]
No, this was in deliberation.

**Comment by jpailthorpe** [comment]
the screens say double down, which comes after deliberation. Pitch>delib>double>decide. Can you clarify then what you mean and what happened here?

**Comment by mattwbenson** [comment]
I'm apparently out of the loop here, so you tell me.

**Comment by jpailthorpe** [comment]
the phase deliberation comes before double down, I just think you found a bug in double down phase is all. here is all the mockups in order if its helpful. We just added yesterday so def. bugs in there im sure. 

https://scene.zeplin.io/project/58a352974ec334e848da2c60


Phase 4: Deliberate (90 seconds)
After each player has had the opportunity to pitch their proposal, the Decider starts the 90 second timer and leads a follow-up discussion with the group. Players (including the Decider) may ask one another for details about each proposal, offer counter arguments, or ask for changes to the proposals. When this 90 seconds is up, The deliberation phase is over and the next phase is advanced automatically. This phase is deliberately left open ended and without direct rules. Players can feel free to do whatever they like, including talking over each other, bashing another’s plan, etc. 

Phase 5: double-down (optional 30 seconds per player) 
At the start of this phase, each player will get a chance to buy 30 seconds of uninterrupted talking time for 100 coins. The option to purchase time will work similarly to the pitch phase, in that player’s will receive the option one at a time, choosing to buy or pass. If a player buys, their time begins immediately. 30 seconds begins and all players see the timer. Once 30 seconds are up, the decider screen informs them to make sure the player stops talking and at the same time the option to buy time is now given to the next player in line. This continues until every players gets a chance to buy or pass. Once it comes back to the original player, that player has a chance to buy or pass again. If ALL players pass in a row, the phase ends and moves to the decide phase.

**Comment by jpailthorpe** [comment]
essentially it operates similarly to deliberation, and in fact, you are somewhat "deliberating" still. but the reason for phase shift is that it has different rules and player interaction stipulations. so to us internally it seems weird and uneeded, but through playtesting with others it becomes needed in order to better understand why there is a difference in rule change.

**Comment by mattwbenson** [comment]
Alright--keep in mind that I have essentially zero idea of what this is supposed to look like. I have been given access to no project docs, no wireframes/mockups, I haven't been a part of any meetings. Please don't make any "assumptions" about what I know, because you're being generous.

**Comment by johnnycrich** [comment]
I am unable to reproduce this currently. Several fixes were made to both pitch and double-down as of this bug being filed, so this may have been resolved as a result.

**Comment by jpailthorpe** [comment]
Matt lets test this !

**Comment by mattwbenson** [comment]
Can't reproduce
