### ISSUE TITLE
Landingpage: Margin problem appearing again on Production landing (iphone6splus) 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/at-stake-v3#97]
on my iphone 6splus, I'm getting wacky center column margins. not a high priority right now, but flagging. 

![img_3251 png](https://cloud.githubusercontent.com/assets/10051544/24807880/ede6513a-1b87-11e7-9a3d-71068c41e538.jpeg)

**Comment by mattwbenson** [comment]
Should be fixed by 6f00938

**Comment by mattwbenson** [comment]
This is fixed on my localhost, possible that issue is connected to how Sass is getting compiled a la #9 , as the fixes are dependent on media queries.

**Comment by jpailthorpe** [comment]
please make sure to check in on this when you review the site
