### ISSUE TITLE
LandingPage: Error Modals appearing on homepage after game crash

### ISSUE THREAD

**Issue by mattwbenson** [engagementgamelab/at-stake-v3#98]
After a game ended due to errors, I navigated back to the landing page URL from the same game window, and had this appear: 

![screen shot 2017-04-07 at 12 28 48 pm](https://cloud.githubusercontent.com/assets/12397944/24809567/e3c30b52-1b8d-11e7-9d75-d1c0bde69332.png)

**Comment by mattwbenson** [comment]
Pushed a rough workaround via 6f00938

**Comment by jpailthorpe** [comment]
fixed
